# Generated by Django 5.2.1 on 2025-08-29 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('especialidad', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Abogado',
                'verbose_name_plural': 'Abogados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion_residencia', models.CharField(blank=True, max_length=255, verbose_name='Dirección de residencia')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Ciudadano',
                'verbose_name_plural': 'Ciudadanos',
            },
        ),
        migrations.CreateModel(
            name='Delito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='Código del delito')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del delito')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Delito',
                'verbose_name_plural': 'Delitos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tiene_segmento_ii', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Segmento',
                'verbose_name_plural': 'Segmentos',
                'ordering': ['tipo_canal', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tipificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tipificación',
                'verbose_name_plural': 'Tipificaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Canal',
                'verbose_name_plural': 'Tipos de Canal',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo documento',
                'verbose_name_plural': 'Tipos de documentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('nivel', models.IntegerField(db_index=True, default=1)),
                ('categoria_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoriapadre', to='gestion.categoria')),
                ('tipificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.tipificacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversacion_id', models.CharField(max_length=250)),
                ('observacion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('cual_otro_delito', models.CharField(blank=True, help_text="Solo se llena cuando se selecciona 'OTROS DELITOS'", max_length=500, null=True, verbose_name='¿Cuál otro delito?')),
                ('se_comunica_uri', models.BooleanField(blank=True, null=True, verbose_name='Se comunica de una URI')),
                ('ciudad_municipio_uri', models.CharField(blank=True, max_length=200, verbose_name='Ciudad/Municipio URI')),
                ('consulta_juridica', models.BooleanField(blank=True, null=True, verbose_name='Consulta jurídica')),
                ('abogado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.abogado', verbose_name='Abogado asignado')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.categoria')),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.ciudadano')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('segmento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.segmento')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CasoAbogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('fecha_tipificacion_agente', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de tipificación del abogado')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('COMPLETADO', 'Completado'), ('CERRADO', 'Cerrado')], default='PENDIENTE', max_length=20)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10)),
                ('observaciones_abogado', models.TextField(blank=True, verbose_name='Observaciones del abogado')),
                ('interaccion_directa_usuario', models.BooleanField(blank=True, null=True, verbose_name='Interacción directa con el usuario')),
                ('habeas_corpus', models.BooleanField(blank=True, null=True, verbose_name='Habeas Corpus')),
                ('tutela', models.BooleanField(blank=True, null=True, verbose_name='Tutela')),
                ('tiempo_respuesta_horas', models.IntegerField(blank=True, null=True, verbose_name='Tiempo de respuesta (horas)')),
                ('abogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_asignados', to='gestion.abogado')),
                ('delito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.delito', verbose_name='Delito identificado')),
                ('evaluacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caso_abogado', to='gestion.evaluacion')),
            ],
            options={
                'verbose_name': 'Caso de Abogado',
                'verbose_name_plural': 'Casos de Abogados',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.pais'),
        ),
        migrations.CreateModel(
            name='RegistroError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=100)),
                ('excepcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentoII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.segmento')),
            ],
            options={
                'verbose_name': 'Segmento II',
                'verbose_name_plural': 'Segmentos II',
                'ordering': ['segmento', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='segmento_ii',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.segmentoii'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='tipificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.tipificacion'),
        ),
        migrations.AddField(
            model_name='segmento',
            name='tipo_canal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.tipocanal'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='tipo_canal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.tipocanal'),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='tipo_identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.tipoidentificacion'),
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['numero_identificacion'], name='gestion_ciu_numero__1b4597_idx'),
        ),
    ]
