# Generated by Django 5.2.1 on 2025-08-31 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SegmentoIII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('segmento_ii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.segmentoii')),
            ],
            options={
                'verbose_name': 'Segmento III',
                'verbose_name_plural': 'Segmentos III',
                'ordering': ['segmento_ii', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='segmento_iii',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.segmentoiii'),
        ),
    ]
