# Generated by Django 5.2.1 on 2025-08-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_segmento_activo_segmentoiii_evaluacion_segmento_iii'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='contacto_correo',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Correo de contacto'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='contacto_telefono',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Teléfono de contacto'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='es_anonimo',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='telefono_inconser',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Teléfono Inconser'),
        ),
    ]
