# Generated by Django 5.2.1 on 2025-08-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_evaluacion_contacto_correo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='telefono_inconser',
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='telefono_inconcer',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Inconcer'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='contacto_telefono_inconcer',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Teléfono Inconcer (contacto)'),
        ),
    ]
