# Generated by Django 5.2.1 on 2025-08-31 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_remove_evaluacion_telefono_inconser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudadano',
            name='telefono_inconcer',
        ),
    ]
