# Generated by Django 5.2.6 on 2025-09-16 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_eval_snapshot_anon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casoabogado',
            name='abogado',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='abogado',
        ),
        migrations.RemoveField(
            model_name='casoabogado',
            name='delito',
        ),
        migrations.RemoveField(
            model_name='casoabogado',
            name='evaluacion',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='ciudad_municipio_uri',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='consulta_juridica',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='cual_otro_delito',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='se_comunica_uri',
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.categoria'),
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominioPersonaAtendio', models.IntegerField(blank=True, null=True)),
                ('satisfaccionServicioRecibido', models.IntegerField(blank=True, null=True)),
                ('tiempoEsperaServicio', models.IntegerField(blank=True, null=True)),
                ('recomendacionCanalAtencion', models.IntegerField(blank=True, null=True)),
                ('solucionSolicitud', models.BooleanField(blank=True, null=True)),
                ('idInteraccion', models.CharField(max_length=150)),
                ('seleccionarCanal', models.CharField(blank=True, max_length=150, null=True)),
                ('nombreAgente', models.CharField(max_length=150)),
                ('token', models.CharField(db_index=True, max_length=50, unique=True)),
                ('fechaExpiracionLink', models.DateTimeField(db_index=True)),
                ('fecha_creacion', models.DateTimeField(db_index=True, null=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encuestas', to='gestion.evaluacion')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SegmentoIV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('segmento_iii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.segmentoiii')),
            ],
            options={
                'verbose_name': 'Segmento IV',
                'verbose_name_plural': 'Segmentos IV',
                'ordering': ['segmento_iii', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='segmento_iv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.segmentoiv'),
        ),
        migrations.CreateModel(
            name='SegmentoV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('segmento_iv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.segmentoiv')),
            ],
            options={
                'verbose_name': 'Segmento V',
                'verbose_name_plural': 'Segmentos V',
                'ordering': ['segmento_iv', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='segmento_v',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.segmentov'),
        ),
        migrations.CreateModel(
            name='SegmentoVI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('segmento_v', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.segmentov')),
            ],
            options={
                'verbose_name': 'Segmento VI',
                'verbose_name_plural': 'Segmentos VI',
                'ordering': ['segmento_v', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='segmento_vi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.segmentovi'),
        ),
        migrations.DeleteModel(
            name='Abogado',
        ),
        migrations.DeleteModel(
            name='Delito',
        ),
        migrations.DeleteModel(
            name='CasoAbogado',
        ),
    ]
