# Generated by Django 5.2.6 on 2025-09-16 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_preguntaencuesta_respuestaencuesta'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='respuestaencuesta',
            name='uniq_encuesta_pregunta',
        ),
        migrations.AlterUniqueTogether(
            name='respuestaencuesta',
            unique_together={('encuesta', 'pregunta')},
        ),
    ]
