# Generated by Django 5.2.6 on 2025-09-17 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_remove_respuestaencuesta_uniq_encuesta_pregunta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroerror',
            options={'ordering': ['-fecha'], 'verbose_name': 'Registro de error', 'verbose_name_plural': 'Registros de error'},
        ),
        migrations.AddField(
            model_name='encuesta',
            name='agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encuestas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='respondida_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='evaluacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encuesta', to='gestion.evaluacion'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='idInteraccion',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='nombreAgente',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['nivel'], name='gestion_cat_nivel_7439fb_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['tipificacion', 'nivel'], name='gestion_cat_tipific_4449e6_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['categoria_padre'], name='gestion_cat_categor_4073bc_idx'),
        ),
        migrations.AddIndex(
            model_name='encuesta',
            index=models.Index(fields=['token'], name='gestion_enc_token_f548f0_idx'),
        ),
        migrations.AddIndex(
            model_name='encuesta',
            index=models.Index(fields=['fechaExpiracionLink'], name='gestion_enc_fechaEx_e312b3_idx'),
        ),
        migrations.AddIndex(
            model_name='encuesta',
            index=models.Index(fields=['respondida_en'], name='gestion_enc_respond_43e74c_idx'),
        ),
        migrations.AddIndex(
            model_name='encuesta',
            index=models.Index(fields=['agente'], name='gestion_enc_agente__287a53_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['fecha'], name='gestion_eva_fecha_65ea82_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['user'], name='gestion_eva_user_id_6fc355_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluacion',
            index=models.Index(fields=['tipo_canal'], name='gestion_eva_tipo_ca_54f373_idx'),
        ),
    ]
